const { test, expect } = require("@playwright/test");
const fs = require("node:fs/promises");
const path = require("node:path");

const STATES = [
  "rest-selection",
  "rest-active",
  "learn",
  "build-size",
  "build-base",
  "build-review",
];

const VIEWPORTS = [
  { name: "1180x820", width: 1180, height: 820 },
  { name: "1024x768", width: 1024, height: 768 },
  { name: "1366x768", width: 1366, height: 768 },
];

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const OUTPUT_ROOT = path.join(REPO_ROOT, "_out", "pod-layout");
const REPORT_PATH = path.join(REPO_ROOT, "POD_LAYOUT_MEASUREMENT_REPORT.md");

async function ensureRendered(page) {
  await page.waitForSelector('[data-pod-lab-ready="true"]', { timeout: 30_000 });
  await page.waitForLoadState("domcontentloaded");
  await page.evaluate(async () => {
    if (document.fonts?.ready) await document.fonts.ready;
    await Promise.all(
      Array.from(document.images)
        .filter((img) => !img.complete)
        .map(
          (img) =>
            new Promise((resolve) => {
              img.addEventListener("load", resolve, { once: true });
              img.addEventListener("error", resolve, { once: true });
              window.setTimeout(resolve, 2500);
            })
        )
    );
  });
  await page.waitForTimeout(300);
}

async function writeMeasurementArtifacts(page, viewport, state, measurement) {
  const dir = path.join(OUTPUT_ROOT, viewport.name);
  await fs.mkdir(dir, { recursive: true });

  const jsonPath = path.join(dir, `${state}.json`);
  const fullScreenshotPath = path.join(dir, `${state}.png`);
  const contentScreenshotPath = path.join(dir, `${state}-content.png`);

  await fs.writeFile(jsonPath, `${JSON.stringify(measurement, null, 2)}\n`);
  await page.screenshot({ path: fullScreenshotPath, fullPage: true });

  const contentRegion = page.locator('[data-pod-layout-region="active-content"]');
  if (await contentRegion.count()) {
    await contentRegion.first().screenshot({ path: contentScreenshotPath });
  }
}

function readFailureText(measurement) {
  const failures = measurement?.failures || [];
  if (!failures.length) return "";

  const details = [];
  if (measurement?.overlaps?.length) {
    details.push(`overlaps=${measurement.overlaps.map((item) => item.name).join(", ")}`);
  }
  if (measurement?.touchTargets?.belowMinimum?.length) {
    details.push(`touch-targets=${measurement.touchTargets.belowMinimum.length}`);
  }
  return [failures.join(", "), ...details].filter(Boolean).join("; ");
}

async function generateSummaryReport() {
  const rows = [];

  for (const viewport of VIEWPORTS) {
    for (const state of STATES) {
      const jsonPath = path.join(OUTPUT_ROOT, viewport.name, `${state}.json`);
      try {
        const measurement = JSON.parse(await fs.readFile(jsonPath, "utf8"));
        rows.push({ viewport: viewport.name, state, measurement });
      } catch {
        rows.push({ viewport: viewport.name, state, measurement: null });
      }
    }
  }

  const lines = [
    "# Pod Layout Measurement Report",
    "",
    "Generated by `npm run pod:measure` from `/dev/pod-lab`.",
    "",
    "| Viewport | State | Page Scroll | Content Scroll | Overlap | Primary Action Visible | Result |",
    "|----------|-------|-------------|----------------|---------|------------------------|--------|",
  ];

  rows.forEach(({ viewport, state, measurement }) => {
    if (!measurement) {
      lines.push(`| ${viewport} | ${state} | missing | missing | missing | missing | missing |`);
      return;
    }

    const pageScroll = measurement.page.verticalOverflow
      ? `${measurement.page.scrollHeight}/${measurement.page.clientHeight}`
      : "no";
    const contentScroll = measurement.regions.activeContent.overflow
      ? `${measurement.regions.activeContent.scrollHeight}/${measurement.regions.activeContent.clientHeight}`
      : "no";
    const overlap = measurement.overlaps.length ? String(measurement.overlaps.length) : "no";
    const primary =
      measurement.primaryActionVisible === null
        ? "n/a"
        : `${measurement.primaryActionVisible ? "yes" : "no"} (${measurement.primaryActionVisiblePercent}%)`;
    const result =
      measurement.result === "pass" ? "pass" : `fail: ${readFailureText(measurement)}`;

    lines.push(
      `| ${viewport} | ${state} | ${pageScroll} | ${contentScroll} | ${overlap} | ${primary} | ${result} |`
    );
  });

  lines.push(
    "",
    "## Region Measurements",
    "",
    "| Viewport | State | Header actual/diff | Hero actual/diff | Content actual/diff | Nav actual/diff |",
    "|----------|-------|--------------------|------------------|---------------------|-----------------|"
  );

  rows.forEach(({ viewport, state, measurement }) => {
    if (!measurement) return;
    const header = measurement.regions.header;
    const hero = measurement.regions.productHero;
    const content = measurement.regions.activeContent;
    const nav = measurement.regions.navigation;
    lines.push(
      `| ${viewport} | ${state} | ${header.actual}/${header.diff} | ${hero.actual}/${hero.diff} | ${content.actual}/${content.diff} | ${nav.actual}/${nav.diff} |`
    );
  });

  lines.push(
    "",
    "## Artifact Locations",
    "",
    "- Full screenshots: `_out/pod-layout/<viewport>/<state>.png`",
    "- Content screenshots: `_out/pod-layout/<viewport>/<state>-content.png`",
    "- JSON reports: `_out/pod-layout/<viewport>/<state>.json`",
    ""
  );

  await fs.writeFile(REPORT_PATH, `${lines.join("\n")}\n`);
}

test.describe.configure({ mode: "serial" });

for (const viewport of VIEWPORTS) {
  for (const state of STATES) {
    test(`${viewport.name} ${state}`, async ({ page }, testInfo) => {
      await page.setViewportSize({ width: viewport.width, height: viewport.height });
      await page.goto(`/dev/pod-lab?state=${state}`, { waitUntil: "domcontentloaded" });
      await ensureRendered(page);

      const measurement = await page.evaluate(() => window.__getPodLayoutMeasurement?.());
      expect(measurement, "Pod layout measurement should be available").toBeTruthy();

      await writeMeasurementArtifacts(page, viewport, state, measurement);
      await generateSummaryReport();

      if (testInfo.project.name === "strict") {
        expect(measurement.failures, readFailureText(measurement)).toEqual([]);
      }
    });
  }
}
