import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const provider = read("src/journey/ActiveJourneyContext.jsx");
const main = read("src/main.jsx");
const api = read("src/lib/api.js");
const store = read("src/state/sessionStore.js");
const ask = read("src/pages/AskSnoozer.jsx");
const cart = read("src/pages/Cart.jsx");
const rest = read("src/hooks/useGuidedRestTest.js");
const results = read("src/pages/Results.jsx");
const pod = read("src/pages/Pod.jsx");
const podBuilder = read("src/components/PodBuilder.jsx");

assert.match(main, /ActiveJourneyProvider/);
assert.match(provider, /useLocation/);
assert.match(provider, /resolveActiveJourney/);
assert.match(provider, /journey_surface_changed/);
assert.doesNotMatch(provider, /setInterval|poll/i);
assert.match(provider, /aria-busy/);
assert.match(api, /\/journey\/resolve/);
assert.match(api, /\/journey\/event/);
assert.match(api, /expectedRevision/);
assert.match(store, /activeJourneyReadyAt/);
assert.match(store, /shopperChanged[\s\S]*activeJourney: null/);
assert.match(ask, /setActiveJourney\(response\.activeJourney\)/);
assert.match(rest, /rest_test_feedback/);
assert.match(rest, /pressure_relief_positive/);
assert.match(pod, /activeJourney\?\.activeConfiguration/);
assert.match(pod, /configuration_changed/);
assert.match(podBuilder, /activeJourneyConfiguration/);
assert.match(cart, /cart_linked/);
assert.match(cart, /checkout_handoff/);
assert.match(results, /allowLocalFallback: !activeJourney\?\.canonicalRecommendation/);
assert.doesNotMatch(store, /cartLines.*activeJourney|activeJourney.*cartLines/);
console.log("Active Journey frontend contract: 21/21 assertions passed");
